version: "3.8"

networks:
  cluster_net:
    external: true
    name: cassandra-net  
  
services:  

  ##################################
  #         CASSANDRA SEED         #
  ##################################         
  seed:
    image: lucasfs/cassandra-armhf
    environment:
      - MAX_HEAP_SIZE=430M
      - HEAP_NEWSIZE=142M
      - CASSANDRA_READ_REQUEST_TIMEOUT_IN_MS=60000
      - CASSANDRA_WRITE_REQUEST_TIMEOUT_IN_MS=60000
      - CASSANDRA_REQUEST_TIMEOUT_IN_MS=60000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == master
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net
    ports:
      - target: 9042
        published: 9042
        mode: host

  ##################################
  #         CASSANDRA NODE         #
  ##################################        
  node:
    image: lucasfs/cassandra-armhf
    environment:
      - SEEDS_SERVICE=seed
      - MAX_HEAP_SIZE=430M
      - HEAP_NEWSIZE=142M
      - TASK_NAME={{.Task.Name}}
      - WAIT_TIME=200
      - CASSANDRA_READ_REQUEST_TIMEOUT_IN_MS=60000
      - CASSANDRA_WRITE_REQUEST_TIMEOUT_IN_MS=60000
      - CASSANDRA_REQUEST_TIMEOUT_IN_MS=60000
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == slave
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net
    ports:
      - target: 9042
        published: 9042
        mode: host
