version: "3.8"

networks:
  cluster_net:
    external:
      name: cassandra-net  
  
services:  

  ################################################################
  # The Casandra cluster 
  #   - cassandra-seed
  ################################################################        
  cassandra-seed:
    image: lucasfs/cassandra-armhf
    environment:
      HEAP_NEWSIZE: 12M
      MAX_HEAP_SIZE: 64M
      CASSANDRA_NUM_TOKENS: 8
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == primary
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net

  ################################################################
  # The Casandra cluster 
  #   - cassandra-node
  ################################################################        
  cassandra:
    image: lucasfs/cassandra-armhf
    environment:
      SEEDS_SERVICE: "cassandra-seed"
      HEAP_NEWSIZE: 12M
      MAX_HEAP_SIZE: 64M
      TASK_NAME: "{{.Task.Name}}"
      WAIT_TIME: 70
      CASSANDRA_NUM_TOKENS: 8
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.type == worker
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net
