version: "3.3"

networks:
  cluster_net:
    external:
      name: cassandra-net  
  
services:  

  ################################################################
  # The Casandra cluster 
  #   - cassandra-node1
  ################################################################        
  cassandra-seed:
    image: cassandra-armhf
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-seed
      - HEAP_NEWSIZE=12M
      - MAX_HEAP_SIZE=64M
      #- TASK_NAME={{.Task.Name}}
      #- WAIT_TIME=60
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.hostname == rpi-04
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    ports:
      - "9042:9042"
    networks:
      - cluster_net

  ################################################################
  # The Casandra cluster 
  #   - cassandra-node2
  ################################################################        
  cassandra-node:
    image: cassandra-armhf
    environment:
      #- CASSANDRA_BROADCAST_ADDRESS=cassandra-node
      - CASSANDRA_SEEDS=cassandra-001
      - HEAP_NEWSIZE=12M
      - MAX_HEAP_SIZE=64M
      - TASK_NAME={{.Task.Name}}
      - WAIT_TIME=40  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.hostname == rpi-03
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net
