version: "3.3"

networks:
  cluster_net:
    external:
      name: cassandra-net  

services:  

  ################################################################
  # The Casandra cluster 
  #   - cassandra-node1
  ################################################################        
  cassandra-001:
    image: lucasfs/cassandra-armhf
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-001
      - MAX_HEAP_SIZE=100m
      - HEAP_NEWSIZE=10m
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        preferences:
          - spread: node.labels.datacenter
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    
  ################################################################
  # The Casandra cluster 
  #   - cassandra-node2
  ################################################################        
  cassandra-002:
    image: lucasfs/cassandra-armhf
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-002
      - CASSANDRA_SEEDS=cassandra-001
      - MAX_HEAP_SIZE=100m
      - HEAP_NEWSIZE=10m
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
      placement:
        preferences:
          - spread: node.labels.datacenter
    volumes:
      - /mnt/storage/cassandra:/var/lib/cassandra 
    networks:
      - cluster_net
